# Generated by Django 4.0.5 on 2022-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_purchase_date",
            field=models.DateField(null=True),
        ),
    ]
