# Generated by Django 4.0.5 on 2022-06-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_order_purchase_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.orderstatus",
            ),
        ),
    ]
